version: "3.4"

services:
  dev:
    platform: linux/amd64
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
      target: dev
    working_dir: /code
    command: [ /bin/bash ]
    volumes:
      - .:/code

  ci-monorepo:
    platform: linux/amd64
    image: ci-monorepo
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
    working_dir: /code
    command: [ /bin/bash ]
    volumes:
      - .:/code

  dev-php-datatypes:
    platform: linux/amd64
    build:
      context: .
      target: dev
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    working_dir: /code/packages/php-datatypes
    volumes:
      - .:/code

  dev-php-table-backend-utils:
    platform: linux/amd64
    build:
      context: .
      target: php-table-backend-utils
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    working_dir: /code/packages/php-table-backend-utils
    volumes:
      - .:/code
    environment:
      - TEST_PREFIX
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      - ABS_CONTAINER_NAME
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_PRIVATE_KEY
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
      - SYNAPSE_UID
      - SYNAPSE_PWD
      - SYNAPSE_DATABASE
      - SYNAPSE_SERVER
      - TERADATA_HOST
      - TERADATA_PORT
      - TERADATA_USERNAME
      - TERADATA_PASSWORD
      - TERADATA_DATABASE
      - EXASOL_HOST
      - EXASOL_USERNAME
      - EXASOL_PASSWORD
      - BQ_KEY_FILE

  ci-php-table-backend-utils:
    platform: linux/amd64
    image: ci-php-table-backend-utils
    build:
      context: .
      target: php-table-backend-utils
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
    environment:
      - TEST_PREFIX
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      - ABS_CONTAINER_NAME
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_PRIVATE_KEY
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
      - SYNAPSE_UID
      - SYNAPSE_PWD
      - SYNAPSE_DATABASE
      - SYNAPSE_SERVER
      - TERADATA_HOST
      - TERADATA_PORT
      - TERADATA_USERNAME
      - TERADATA_PASSWORD
      - TERADATA_DATABASE
      - EXASOL_HOST
      - EXASOL_USERNAME
      - EXASOL_PASSWORD
      - BQ_KEY_FILE

  dev-php-db-import-export:
    platform: linux/amd64
    build:
      context: .
      target: php-db-import-export
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    environment:
      - IE_ABS_ACCOUNT_NAME
      - IE_ABS_ACCOUNT_KEY
      - IE_ABS_CONTAINER_NAME
      - IE_SNOWFLAKE_HOST
      - IE_SNOWFLAKE_PORT
      - IE_SNOWFLAKE_USER
      - IE_SNOWFLAKE_PASSWORD
      - IE_SNOWFLAKE_DATABASE
      - IE_SNOWFLAKE_WAREHOUSE
      - IE_SYNAPSE_UID
      - IE_SYNAPSE_PWD
      - IE_SYNAPSE_DATABASE
      - IE_SYNAPSE_SERVER
      - IE_AWS_ACCESS_KEY_ID
      - IE_AWS_SECRET_ACCESS_KEY
      - IE_AWS_S3_BUCKET
      - IE_AWS_S3_KEY
      - IE_AWS_REGION
      - IE_EXASOL_HOST
      - IE_EXASOL_USERNAME
      - IE_EXASOL_PASSWORD
      - IE_BUILD_PREFIX
      - IE_TERADATA_HOST
      - IE_TERADATA_USERNAME
      - IE_TERADATA_PASSWORD
      - IE_TERADATA_PORT
      - IE_TERADATA_DATABASE
      - IE_ABS_TERADATA_HOST
      - IE_ABS_TERADATA_USERNAME
      - IE_ABS_TERADATA_PASSWORD
      - IE_ABS_TERADATA_PORT
      - IE_ABS_TERADATA_DATABASE
      - IE_GITHUB_OAUTH_TOKEN
      - IE_STORAGE_TYPE
      - IE_GCS_CREDENTIALS
      - IE_GCS_BUCKET_NAME
      - IE_GCS_INTEGRATION_NAME
      - IE_BQ_KEY_FILE
      - IE_BQ_BUCKET_NAME
      - IE_SUITE
    working_dir: /code/packages/php-db-import-export
    volumes:
      - .:/code

  ci-php-db-import-export:
    platform: linux/amd64
    image: ci-php-db-import-export
    build:
      context: .
      target: php-db-import-export
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
    environment:
      - ABS_ACCOUNT_NAME
      - ABS_ACCOUNT_KEY
      - ABS_CONTAINER_NAME
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
      - SYNAPSE_UID
      - SYNAPSE_PWD
      - SYNAPSE_DATABASE
      - SYNAPSE_SERVER
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_S3_KEY
      - AWS_REGION
      - EXASOL_HOST
      - EXASOL_USERNAME
      - EXASOL_PASSWORD
      - BUILD_PREFIX
      - TERADATA_HOST
      - TERADATA_USERNAME
      - TERADATA_PASSWORD
      - TERADATA_PORT
      - TERADATA_DATABASE
      - ABS_TERADATA_HOST
      - ABS_TERADATA_USERNAME
      - ABS_TERADATA_PASSWORD
      - ABS_TERADATA_PORT
      - ABS_TERADATA_DATABASE
      - GITHUB_OAUTH_TOKEN
      - STORAGE_TYPE
      - GCS_CREDENTIALS
      - GCS_BUCKET_NAME
      - GCS_INTEGRATION_NAME
      - BQ_KEY_FILE
      - BQ_BUCKET_NAME
      - SUITE

  exasol:
    image: exasol/docker-db:latest-7.1
    privileged: true
    volumes:
      - exa-volume:/exa

  dev-php-storage-driver-common:
    platform: linux/amd64
    build:
      context: .
      target: php-storage-driver-common
      args:
        - GITHUB_OAUTH_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
    environment:
      - DEBUG
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - BUILD_PREFIX
    working_dir: /code/packages/php-storage-driver-common
    volumes:
      - ./:/code

  ci-php-storage-driver-common:
    platform: linux/amd64
    image: php-storage-driver-common
    build:
      context: .
      target: php-storage-driver-common
      args:
        - GITHUB_OAUTH_TOKEN
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
    environment:
      - DEBUG
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_S3_BUCKET
      - AWS_REGION
      - BUILD_PREFIX

volumes:
  exa-volume:
