# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/backend/bigQuery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/backend/bigQuery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/backend/bigQuery.proto\x12&keboola.storageDriver.backend.bigQuery\"E\n\x10TimePartitioning\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0c\x65xpirationMs\x18\x02 \x01(\t\x12\r\n\x05\x66ield\x18\x03 \x01(\t\"\xa9\x01\n\x11RangePartitioning\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12N\n\x05range\x18\x02 \x01(\x0b\x32?.keboola.storageDriver.backend.bigQuery.RangePartitioning.Range\x1a\x35\n\x05Range\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\t\x12\x10\n\x08interval\x18\x03 \x01(\t\"\x1c\n\nClustering\x12\x0e\n\x06\x66ields\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.backend.bigQuery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMEPARTITIONING']._serialized_start=72
  _globals['_TIMEPARTITIONING']._serialized_end=141
  _globals['_RANGEPARTITIONING']._serialized_start=144
  _globals['_RANGEPARTITIONING']._serialized_end=313
  _globals['_RANGEPARTITIONING_RANGE']._serialized_start=260
  _globals['_RANGEPARTITIONING_RANGE']._serialized_end=313
  _globals['_CLUSTERING']._serialized_start=315
  _globals['_CLUSTERING']._serialized_end=343
# @@protoc_insertion_point(module_scope)
