sudo: required

language: bash
dist: focal

services:
  - docker

before_script:
  - docker -v
  # install dependencies
  - sudo apt-get -y install parallel
  - parallel --version
  - >-
    parallel -j5 --linebuffer docker pull :::
    quay.io/keboola/azure-cli
    exasol/docker-db:latest
    php:7.1-cli
  - docker-compose build production
  #create synapse server
  - . ./provisioning/synapse/synapse.sh -c
  - echo $SYNAPSE_RESOURCE_ID
script:
  - echo $SYNAPSE_RESOURCE_ID
  # prepare docker network
  - docker network create php-table-backend-utils_default
  #Run Exasol server
  - docker-compose up -d exasol
  - export EXASOL_HOST=exasol:8563
  - export EXASOL_USERNAME=sys
  - export EXASOL_PASSWORD=exasol
  # run ci
  - docker-compose run production composer ci
  - docker-compose stop
after_script:
  # delete synapse
  - ./provisioning/synapse/synapse.sh -d
