sudo: required

language: bash
dist: focal

services:
  - docker

before_script:
  - docker -v
  # install dependencies
  - sudo apt-get -y install parallel
  - parallel --version
  - docker-compose build production
  - docker pull quay.io/keboola/azure-cli
  #create synapse server
  - . ./provisioning/synapse/synapse.sh -c
  - echo $SYNAPSE_RESOURCE_ID
script:
  - echo $SYNAPSE_RESOURCE_ID
  # prepare docker network
  - docker network create php-table-backend-utils_default
  # run ci
  - docker-compose run production composer ci
after_script:
  # delete synapse
  - ./provisioning/synapse/synapse.sh -d
