sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  # install dependencies
  - sudo apt-get -y install parallel
  - parallel --version
  - docker-compose build production
  #create synapse server
  - . ./provisioning/synapse/synapse.sh -c
script:
  - echo $SYNAPSE_RESOURCE_ID
  # prepare docker network
  - docker network create php-table-backend-utils_default

  #run CI stuff
  - >-
    parallel -j12 --linebuffer docker-compose run production composer :::
    phplint
    phpcs
    phpstan

  # Run unit tests
  - docker-compose run production composer tests-unit
  # Run functional tests
  - docker-compose run production composer tests-functional
after_script:
  # delete synapse
  - ./provisioning/synapse/synapse.sh -d
