<?php

declare(strict_types=1);

namespace Tests\Keboola\Db\ImportExportFunctional\Snowflake\Exporter;

use Keboola\Db\ImportExport\Backend\Snowflake\Export\Exporter;
use Keboola\Db\ImportExport\ExportFileType;
use Keboola\Db\ImportExport\ExportOptions;
use Keboola\Db\ImportExport\Storage;
use Keboola\TableBackendUtils\Escaping\Snowflake\SnowflakeQuote;
use Tests\Keboola\Db\ImportExportFunctional\Snowflake\SnowflakeBaseTestCase;

class ParquetExportTest extends SnowflakeBaseTestCase
{
    public const TESTS_PREFIX = 'parquet_export_test_';

    protected function getTestTableName(): string
    {
        return self::TESTS_PREFIX . uniqid();
    }

    public function setUp(): void
    {
        parent::setUp();
        $this->clearDestination($this->getExportDir());
        $this->cleanSchema($this->getDestinationSchemaName());
        $this->cleanSchema($this->getSourceSchemaName());
        $this->createSchema($this->getSourceSchemaName());
        $this->createSchema($this->getDestinationSchemaName());
    }

    private function createTestTable(string $tableName): void
    {
        $this->connection->executeQuery(sprintf(
            'CREATE TABLE %s (
                "ID" INTEGER,
                "STRING_COL" VARCHAR(255),
                "NUMBER_COL" NUMERIC(10,2),
                "DATE_COL" DATE,
                "BOOL_COL" BOOLEAN
            )',
            $this->connection->quoteIdentifier($tableName),
        ));

        // Insert test data
        $this->connection->executeQuery(sprintf(
            'INSERT INTO %s ("ID", "STRING_COL", "NUMBER_COL", "DATE_COL", "BOOL_COL") VALUES
            (1, \'test string\', 123.45, \'2024-01-01\', TRUE),
            (2, \'another string\', 678.90, \'2024-02-01\', FALSE)',
            $this->connection->quoteIdentifier($tableName),
        ));
    }

    public function testExportSimpleToParquet(): void
    {
        $tableName = $this->getTestTableName();
        $this->createTestTable($tableName);

        $source = new Storage\Snowflake\Table(
            $this->getDestinationSchemaName(),
            $tableName,
        );

        $options = new ExportOptions(
            isCompressed: false,
            generateManifest: ExportOptions::MANIFEST_AUTOGENERATED,
            fileType: ExportFileType::PARQUET,
        );
        /** @var Storage\S3\DestinationFile $destination */
        $destination = $this->getDestinationInstance($this->getExportDir() . '/parquet_test');

        $result = (new Exporter($this->connection))->exportTable(
            $source,
            $destination,
            $options,
        );

        $this->assertCount(1, $result);
        /** @var array<mixed> $slice */
        $slice = reset($result);

        $this->assertArrayHasKey('FILE_NAME', $slice);
        $this->assertArrayHasKey('FILE_SIZE', $slice);
        $this->assertArrayHasKey('ROW_COUNT', $slice);

        $this->assertStringEndsWith('.parquet', $slice['FILE_NAME']);
        $this->assertNotEmpty($slice['FILE_SIZE']);
        $this->assertSame(2, (int) $slice['ROW_COUNT']);

        $files = $this->getFileNames($this->getExportDir(), false);
        $this->assertContains($this->getExportDir() . '/parquet_testmanifest', array_values($files));

        $files = $this->listFiles($this->getExportDir());
        $tmpFiles = $this->getParquetFileFromStorage($files);
        $content = $this->getParquetContent($tmpFiles);
        $this->assertSame([
            [
                'ID' => 1.0,
                'STRING_COL' => 'test string',
                'NUMBER_COL' => 123.45,
                'DATE_COL' => '2024-01-01T00:00:00+00:00',
                'BOOL_COL' => true,
            ],
            [
                'ID' => 2.0,
                'STRING_COL' => 'another string',
                'NUMBER_COL' => 678.9,
                'DATE_COL' => '2024-02-01T00:00:00+00:00',
                'BOOL_COL' => false,
            ],
        ], $content);
    }

    public function testExportCompressedParquet(): void
    {
        $tableName = $this->getTestTableName();
        $this->createTestTable($tableName);

        $source = new Storage\Snowflake\SelectSource(sprintf(
            'SELECT * FROM %s',
            $this->connection->quoteIdentifier($tableName),
        ));

        $options = new ExportOptions(
            isCompressed: true,
            generateManifest: ExportOptions::MANIFEST_AUTOGENERATED,
            fileType: ExportFileType::PARQUET,
        );
        /** @var Storage\S3\DestinationFile $destination */
        $destination = $this->getDestinationInstance($this->getExportDir() . '/parquet_compressed_test');

        $result = (new Exporter($this->connection))->exportTable(
            $source,
            $destination,
            $options,
        );

        $this->assertCount(1, $result);
        /** @var array<mixed> $slice */
        $slice = reset($result);

        $this->assertArrayHasKey('FILE_NAME', $slice);
        $this->assertArrayHasKey('FILE_SIZE', $slice);
        $this->assertArrayHasKey('ROW_COUNT', $slice);

        $this->assertStringEndsWith('.parquet', $slice['FILE_NAME']);
        $this->assertNotEmpty($slice['FILE_SIZE']);
        $this->assertSame(2, (int) $slice['ROW_COUNT']);

        $files = $this->getFileNames($this->getExportDir(), false);
        $this->assertContains($this->getExportDir() . '/parquet_compressed_testmanifest', array_values($files));

        $files = $this->listFiles($this->getExportDir());
        $tmpFiles = $this->getParquetFileFromStorage($files);
        $content = $this->getParquetContent($tmpFiles);
        $this->assertSame([
            [
                'ID' => 1.0,
                'STRING_COL' => 'test string',
                'NUMBER_COL' => 123.45,
                'DATE_COL' => '2024-01-01T00:00:00+00:00',
                'BOOL_COL' => true,
            ],
            [
                'ID' => 2.0,
                'STRING_COL' => 'another string',
                'NUMBER_COL' => 678.9,
                'DATE_COL' => '2024-02-01T00:00:00+00:00',
                'BOOL_COL' => false,
            ],
        ], $content);
    }

    public function testExportParquetWithTimezone(): void
    {
        $tableName = $this->getTestTableName();
        $schema = SnowflakeQuote::quoteSingleIdentifier($this->getDestinationSchemaName());
        $table = SnowflakeQuote::quoteSingleIdentifier($tableName);

        $this->connection->executeQuery(sprintf(
            'CREATE TABLE %s.%s (
                "ID" INTEGER,
                "TS" TIMESTAMP_LTZ
            )',
            $schema,
            $table,
        ));

        // Insert with explicit UTC timezone for deterministic values
        $this->connection->executeStatement("ALTER SESSION SET TIMEZONE = 'UTC'");
        $this->connection->executeQuery(sprintf(
            'INSERT INTO %s.%s ("ID", "TS") VALUES
            (1, \'2024-01-15 12:00:00\'),
            (2, \'2024-07-15 12:00:00\')',
            $schema,
            $table,
        ));
        $this->connection->executeStatement('ALTER SESSION UNSET TIMEZONE');

        $source = new Storage\Snowflake\Table(
            $this->getDestinationSchemaName(),
            $tableName,
        );
        $options = new ExportOptions(
            isCompressed: false,
            generateManifest: ExportOptions::MANIFEST_SKIP,
            fileType: ExportFileType::PARQUET,
            timezone: 'America/Los_Angeles',
        );
        /** @var Storage\S3\DestinationFile $destination */
        $destination = $this->getDestinationInstance($this->getExportDir() . '/parquet_tz_test');

        $result = (new Exporter($this->connection))->exportTable(
            $source,
            $destination,
            $options,
        );

        $this->assertCount(1, $result);
        /** @var array{FILE_NAME: string, FILE_SIZE: string, ROW_COUNT: string} $slice */
        $slice = reset($result);
        $this->assertSame(2, (int) $slice['ROW_COUNT']);

        $files = $this->listFiles($this->getExportDir());
        $tmpFiles = $this->getParquetFileFromStorage($files);
        $content = $this->getParquetContent($tmpFiles);

        usort($content, fn($a, $b) => $a['ID'] <=> $b['ID']);

        $ts1 = $content[0]['TS'];
        $ts2 = $content[1]['TS'];
        assert(is_string($ts1));
        assert(is_string($ts2));
        // January: PST = UTC-8, so 12:00 UTC -> 04:00 PST
        $this->assertStringStartsWith('2024-01-15T04:00:00', $ts1);
        // July: PDT = UTC-7, so 12:00 UTC -> 05:00 PDT
        $this->assertStringStartsWith('2024-07-15T05:00:00', $ts2);
    }

    public function testExportParquetTimezoneDoesNotAffectSession(): void
    {
        $tableName = $this->getTestTableName();
        $schema = SnowflakeQuote::quoteSingleIdentifier($this->getDestinationSchemaName());
        $table = SnowflakeQuote::quoteSingleIdentifier($tableName);

        $this->connection->executeQuery(sprintf(
            'CREATE TABLE %s.%s (
                "ID" INTEGER,
                "TS" TIMESTAMP_LTZ
            )',
            $schema,
            $table,
        ));

        $this->connection->executeStatement("ALTER SESSION SET TIMEZONE = 'UTC'");
        $this->connection->executeQuery(sprintf(
            'INSERT INTO %s.%s ("ID", "TS") VALUES (1, \'2024-01-15 12:00:00\')',
            $schema,
            $table,
        ));
        $this->connection->executeStatement('ALTER SESSION UNSET TIMEZONE');

        $timezoneBefore = $this->connection->fetchOne('SELECT CURRENT_TIMEZONE()');

        $source = new Storage\Snowflake\Table(
            $this->getDestinationSchemaName(),
            $tableName,
        );
        $options = new ExportOptions(
            isCompressed: false,
            generateManifest: ExportOptions::MANIFEST_SKIP,
            fileType: ExportFileType::PARQUET,
            timezone: 'Pacific/Auckland',
        );
        /** @var Storage\S3\DestinationFile $destination */
        $destination = $this->getDestinationInstance($this->getExportDir() . '/parquet_tz_restore');

        (new Exporter($this->connection))->exportTable(
            $source,
            $destination,
            $options,
        );

        $timezoneAfter = $this->connection->fetchOne('SELECT CURRENT_TIMEZONE()');
        $this->assertSame($timezoneBefore, $timezoneAfter);
    }

    public function testExportParquetWithQuery(): void
    {
        $tableName = $this->getTestTableName();
        $this->createTestTable($tableName);

        // Use a query that transforms the data
        $source = new Storage\Snowflake\SelectSource(sprintf(
            'SELECT * FROM %s',
            $this->connection->quoteIdentifier($tableName),
        ));

        $options = new ExportOptions(
            isCompressed: false,
            generateManifest: ExportOptions::MANIFEST_AUTOGENERATED,
            fileType: ExportFileType::PARQUET,
        );
        /** @var Storage\S3\DestinationFile $destination */
        $destination = $this->getDestinationInstance($this->getExportDir() . '/parquet_query_test');

        $result = (new Exporter($this->connection))->exportTable(
            $source,
            $destination,
            $options,
        );

        $this->assertCount(1, $result);
        /** @var array<mixed> $slice */
        $slice = reset($result);

        $this->assertArrayHasKey('FILE_NAME', $slice);
        $this->assertArrayHasKey('FILE_SIZE', $slice);
        $this->assertArrayHasKey('ROW_COUNT', $slice);

        $this->assertStringEndsWith('.parquet', $slice['FILE_NAME']);
        $this->assertNotEmpty($slice['FILE_SIZE']);
        $this->assertSame(2, (int) $slice['ROW_COUNT']);

        $files = $this->getFileNames($this->getExportDir(), false);
        $this->assertContains($this->getExportDir() . '/parquet_query_testmanifest', array_values($files));

        $files = $this->listFiles($this->getExportDir());
        $tmpFiles = $this->getParquetFileFromStorage($files);
        $content = $this->getParquetContent($tmpFiles);

        $this->assertSame([
            [
                'ID' => 1.0,
                'STRING_COL' => 'test string',
                'NUMBER_COL' => 123.45,
                'DATE_COL' => '2024-01-01T00:00:00+00:00',
                'BOOL_COL' => true,
            ],
            [
                'ID' => 2.0,
                'STRING_COL' => 'another string',
                'NUMBER_COL' => 678.9,
                'DATE_COL' => '2024-02-01T00:00:00+00:00',
                'BOOL_COL' => false,
            ],
        ], $content);
    }
}
