# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/backend.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/backend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/backend.proto\x12%keboola.storageDriver.command.backend\x1a\x19google/protobuf/any.proto\"8\n\x12InitBackendCommand\x12\"\n\x04meta\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"k\n\x13InitBackendResponse\x12\"\n\x04meta\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x1a\x30\n\x16InitBackendSynapseMeta\x12\x16\n\x0eglobalRoleName\x18\x01 \x01(\t\":\n\x14RemoveBackendCommand\x12\"\n\x04meta\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.backend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITBACKENDCOMMAND']._serialized_start=89
  _globals['_INITBACKENDCOMMAND']._serialized_end=145
  _globals['_INITBACKENDRESPONSE']._serialized_start=147
  _globals['_INITBACKENDRESPONSE']._serialized_end=254
  _globals['_INITBACKENDRESPONSE_INITBACKENDSYNAPSEMETA']._serialized_start=206
  _globals['_INITBACKENDRESPONSE_INITBACKENDSYNAPSEMETA']._serialized_end=254
  _globals['_REMOVEBACKENDCOMMAND']._serialized_start=256
  _globals['_REMOVEBACKENDCOMMAND']._serialized_end=314
# @@protoc_insertion_point(module_scope)
