# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/common.proto\x12$keboola.storageDriver.command.common\x1a\x19google/protobuf/any.proto\"\xc1\x01\n\rDriverRequest\x12)\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12%\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x10\n\x08\x66\x65\x61tures\x18\x03 \x03(\t\x12L\n\x0eruntimeOptions\x18\x04 \x01(\x0b\x32\x34.keboola.storageDriver.command.common.RuntimeOptions\"\xcd\x01\n\x0eRuntimeOptions\x12\r\n\x05runId\x18\x01 \x01(\t\x12V\n\tqueryTags\x18\x03 \x03(\x0b\x32\x43.keboola.storageDriver.command.common.RuntimeOptions.QueryTagsEntry\x12\"\n\x04meta\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x1a\x30\n\x0eQueryTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xfe\x01\n\nLogMessage\x12\x45\n\x05level\x18\x01 \x01(\x0e\x32\x36.keboola.storageDriver.command.common.LogMessage.Level\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"q\n\x05Level\x12\r\n\tEmergency\x10\x00\x12\t\n\x05\x41lert\x10\x01\x12\x0c\n\x08\x43ritical\x10\x02\x12\t\n\x05\x45rror\x10\x03\x12\x0b\n\x07Warning\x10\x04\x12\n\n\x06Notice\x10\x05\x12\x11\n\rInformational\x10\x06\x12\t\n\x05\x44\x65\x62ug\x10\x07\"\x83\x01\n\x0e\x44riverResponse\x12-\n\x0f\x63ommandResponse\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x42\n\x08messages\x18\x02 \x03(\x0b\x32\x30.keboola.storageDriver.command.common.LogMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNTIMEOPTIONS_QUERYTAGSENTRY']._loaded_options = None
  _globals['_RUNTIMEOPTIONS_QUERYTAGSENTRY']._serialized_options = b'8\001'
  _globals['_DRIVERREQUEST']._serialized_start=88
  _globals['_DRIVERREQUEST']._serialized_end=281
  _globals['_RUNTIMEOPTIONS']._serialized_start=284
  _globals['_RUNTIMEOPTIONS']._serialized_end=489
  _globals['_RUNTIMEOPTIONS_QUERYTAGSENTRY']._serialized_start=441
  _globals['_RUNTIMEOPTIONS_QUERYTAGSENTRY']._serialized_end=489
  _globals['_LOGMESSAGE']._serialized_start=492
  _globals['_LOGMESSAGE']._serialized_end=746
  _globals['_LOGMESSAGE_LEVEL']._serialized_start=633
  _globals['_LOGMESSAGE_LEVEL']._serialized_end=746
  _globals['_DRIVERRESPONSE']._serialized_start=749
  _globals['_DRIVERRESPONSE']._serialized_end=880
# @@protoc_insertion_point(module_scope)
