# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/credentials.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/credentials.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/credentials.proto\x12!keboola.storageDriver.credentials\x1a\x19google/protobuf/any.proto\"\xdf\x03\n\x19GenericBackendCredentials\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x11\n\tprincipal\x18\x02 \x01(\t\x12\x0e\n\x06secret\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\r\x12\"\n\x04meta\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any\x1a+\n\x17RedshiftCredentialsMeta\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x1a+\n\x17TeradataCredentialsMeta\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x1a\x7f\n\x18SnowflakeCredentialsMeta\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x11\n\twarehouse\x18\x02 \x01(\t\x12(\n workspaceStatementTimeoutSeconds\x18\x03 \x01(\r\x12\x14\n\x0ctracingLevel\x18\x04 \x01(\r\x1a\x46\n\x16SynapseCredentialsMeta\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x1a\n\x12useManagedIdentity\x18\x02 \x01(\x08\x1a<\n\x17\x42igQueryCredentialsMeta\x12\x11\n\tfolder_id\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERICBACKENDCREDENTIALS']._serialized_start=90
  _globals['_GENERICBACKENDCREDENTIALS']._serialized_end=569
  _globals['_GENERICBACKENDCREDENTIALS_REDSHIFTCREDENTIALSMETA']._serialized_start=218
  _globals['_GENERICBACKENDCREDENTIALS_REDSHIFTCREDENTIALSMETA']._serialized_end=261
  _globals['_GENERICBACKENDCREDENTIALS_TERADATACREDENTIALSMETA']._serialized_start=263
  _globals['_GENERICBACKENDCREDENTIALS_TERADATACREDENTIALSMETA']._serialized_end=306
  _globals['_GENERICBACKENDCREDENTIALS_SNOWFLAKECREDENTIALSMETA']._serialized_start=308
  _globals['_GENERICBACKENDCREDENTIALS_SNOWFLAKECREDENTIALSMETA']._serialized_end=435
  _globals['_GENERICBACKENDCREDENTIALS_SYNAPSECREDENTIALSMETA']._serialized_start=437
  _globals['_GENERICBACKENDCREDENTIALS_SYNAPSECREDENTIALSMETA']._serialized_end=507
  _globals['_GENERICBACKENDCREDENTIALS_BIGQUERYCREDENTIALSMETA']._serialized_start=509
  _globals['_GENERICBACKENDCREDENTIALS_BIGQUERYCREDENTIALSMETA']._serialized_end=569
# @@protoc_insertion_point(module_scope)
