# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/executeQuery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/executeQuery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/executeQuery.proto\x12*keboola.storageDriver.command.executeQuery\"\xac\x03\n\x13\x45xecuteQueryCommand\x12\x17\n\x0fpathRestriction\x18\x01 \x03(\t\x12\x0f\n\x07timeout\x18\x02 \x01(\r\x12\r\n\x05query\x18\x03 \x01(\t\x12\x66\n\rsnowflakeRole\x18\x04 \x01(\x0b\x32M.keboola.storageDriver.command.executeQuery.ExecuteQueryCommand.SnowflakeRoleH\x00\x12x\n\x16\x62igQueryServiceAccount\x18\x05 \x01(\x0b\x32V.keboola.storageDriver.command.executeQuery.ExecuteQueryCommand.BigQueryServiceAccountH\x00\x1a!\n\rSnowflakeRole\x12\x10\n\x08roleName\x18\x01 \x01(\t\x1aH\n\x16\x42igQueryServiceAccount\x12\x1b\n\x13serviceAccountEmail\x18\x01 \x01(\t\x12\x11\n\tprojectId\x18\x02 \x01(\tB\r\n\x0brestriction\"\x88\x04\n\x14\x45xecuteQueryResponse\x12W\n\x06status\x18\x01 \x01(\x0e\x32G.keboola.storageDriver.command.executeQuery.ExecuteQueryResponse.Status\x12S\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x45.keboola.storageDriver.command.executeQuery.ExecuteQueryResponse.Data\x12\x0f\n\x07message\x18\x03 \x01(\t\x1a\x8e\x02\n\x04\x44\x61ta\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\t\x12W\n\x04rows\x18\x02 \x03(\x0b\x32I.keboola.storageDriver.command.executeQuery.ExecuteQueryResponse.Data.Row\x1a\x9b\x01\n\x03Row\x12\x65\n\x06\x66ields\x18\x01 \x03(\x0b\x32U.keboola.storageDriver.command.executeQuery.ExecuteQueryResponse.Data.Row.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x06Status\x12\x0b\n\x07Success\x10\x00\x12\t\n\x05\x45rror\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.executeQuery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEQUERYRESPONSE_DATA_ROW_FIELDSENTRY']._loaded_options = None
  _globals['_EXECUTEQUERYRESPONSE_DATA_ROW_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTEQUERYCOMMAND']._serialized_start=73
  _globals['_EXECUTEQUERYCOMMAND']._serialized_end=501
  _globals['_EXECUTEQUERYCOMMAND_SNOWFLAKEROLE']._serialized_start=379
  _globals['_EXECUTEQUERYCOMMAND_SNOWFLAKEROLE']._serialized_end=412
  _globals['_EXECUTEQUERYCOMMAND_BIGQUERYSERVICEACCOUNT']._serialized_start=414
  _globals['_EXECUTEQUERYCOMMAND_BIGQUERYSERVICEACCOUNT']._serialized_end=486
  _globals['_EXECUTEQUERYRESPONSE']._serialized_start=504
  _globals['_EXECUTEQUERYRESPONSE']._serialized_end=1024
  _globals['_EXECUTEQUERYRESPONSE_DATA']._serialized_start=720
  _globals['_EXECUTEQUERYRESPONSE_DATA']._serialized_end=990
  _globals['_EXECUTEQUERYRESPONSE_DATA_ROW']._serialized_start=835
  _globals['_EXECUTEQUERYRESPONSE_DATA_ROW']._serialized_end=990
  _globals['_EXECUTEQUERYRESPONSE_DATA_ROW_FIELDSENTRY']._serialized_start=945
  _globals['_EXECUTEQUERYRESPONSE_DATA_ROW_FIELDSENTRY']._serialized_end=990
  _globals['_EXECUTEQUERYRESPONSE_STATUS']._serialized_start=992
  _globals['_EXECUTEQUERYRESPONSE_STATUS']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
