sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  # Send resume to synapse server in background
  - bash docker/synapse/synapse.sh -r &
  # install dependencies
  - sudo apt-get -y install parallel
  - parallel --version
  - docker-compose build production
  - docker pull quay.io/keboola/azure-cli
  #create synapse server
  - . ./provisioning/synapse/synapse.sh -c
  # prepare docker network
  - docker network create php-db-import-export_default
script:
  #run CI stuff
  - >-
    parallel -j12 --linebuffer docker-compose run production composer :::
    phplint
    phpcs
    phpstan
    loadAbs
    init-synapse

  # Run unit tests
  - docker-compose run production composer tests-unit

  # run parallel functional tests
  - >-
    travis_wait 60 parallel -j12 --linebuffer docker-compose run production composer :::
    tests-snowflake
    tests-synapse
after_script:
  # delete synapse
  - bash ./provisioning/synapse/synapse.sh -d
