sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  # Send resume to synapse server in background
  - bash docker/synapse/synapse.sh -r &
  # install dependencies
  - sudo apt-get -y install parallel
  - parallel --version
  - docker-compose build production
script:
  # prepare docker network
  - docker network create php-db-import-export_default

  #run CI stuff
  - >-
    parallel -j12 --linebuffer docker-compose run production composer :::
    phplint
    phpcs
    phpstan
    loadAbs

  # Run unit tests
  - docker-compose run production composer tests-unit

  # wait for Synapse to start, should be already online
  - bash docker/synapse/synapse.sh -w

  # run parallel functional tests
  - >-
    travis_wait 60 parallel -j12 --linebuffer docker-compose run production composer :::
    tests-snowflake
    tests-synapse
after_script:
  # Send pause to synapse server in background
  - bash docker/synapse/synapse.sh -p &
