sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  # Send resume to synapse server in background
  - bash docker/synapse/synapse.sh -r &
  # install dependencies
  - sudo apt-get -y install parallel
  - parallel --version
  - docker-compose build production
script:
  # prepare docekr network
  - docker network create php-db-import-export_default
  #run CI stuff
  - >-
    parallel -j12 --linebuffer docker-compose run production composer :::
    phplint
    phpcs
    phpstan
    loadAbs
    tests-unit
  # prepare tests
  - echo -n > commands
  - echo 'synapse     -;bash docker/synapse/synapse.sh -w && docker-compose run production php ./vendor/bin/phpunit --debug --colors=always --testsuite synapse' >> commands
  - echo 'snowflake   -;docker-compose run production php ./vendor/bin/phpunit --debug --colors=always --testsuite snowflake' >> commands
  # run parallel functional tests
  - parallel -j12 --linebuffer --colsep ';' --tagstring {1} -a commands bash -c {2}
after_script:
  # Send pause to synapse server in background
  - bash docker/synapse/synapse.sh -p &
