language: php

services:
  - docker

before_script:
  - composer update

script:
  - composer ci

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

jobs:
  include:
    - php: 5.6
      script:
        - composer phplint
