language: php

services:
  - docker

before_script:
  - composer install

script:
  - composer ci

php:
  - 7.1
  - 7.2
  - 7.3

jobs:
  include:
    - php: 5.6
      before_script:
        - php generate-composer56.php
        - composer install
