version: "2"

services:

  dev:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    command: sh -c 'composer install -n && php ./vendor/bin/phpunit'
    tty: true
    stdin_open: true
