<?php

declare(strict_types=1);

namespace Tests\Keboola\Db\ImportExportFunctional\Bigquery\Exporter;

use Keboola\Csv\CsvFile;
use Keboola\CsvOptions\CsvOptions;
use Keboola\Db\ImportExport\Backend\Bigquery\Export\Exporter;
use Keboola\Db\ImportExport\Backend\Bigquery\ToFinalTable\FullImporter;
use Keboola\Db\ImportExport\Backend\Bigquery\ToStage\StageTableDefinitionFactory;
use Keboola\Db\ImportExport\Backend\Bigquery\ToStage\ToStageImporter;
use Keboola\Db\ImportExport\ExportOptions;
use Keboola\Db\ImportExport\ImportOptions;
use Keboola\Db\ImportExport\Storage;
use Keboola\TableBackendUtils\Table\Bigquery\BigqueryTableDefinition;
use Keboola\TableBackendUtils\Table\Bigquery\BigqueryTableQueryBuilder;
use Keboola\TableBackendUtils\Table\Bigquery\BigqueryTableReflection;
use Tests\Keboola\Db\ImportExportFunctional\Bigquery\BigqueryBaseTestCase;

class ExportTest extends BigqueryBaseTestCase
{
    public function setUp(): void
    {
        parent::setUp();
        $this->clearDestination($this->getExportDir());
        $this->cleanDatabase($this->getDestinationDbName());
        $this->createDatabase($this->getDestinationDbName());

        $this->cleanDatabase($this->getSourceDbName());
        $this->createDatabase($this->getSourceDbName());
    }

    public function tearDown(): void
    {
        parent::tearDown();
    }

    public function testExportGzip(): void
    {
        $this->initTable(self::TABLE_OUT_CSV_2COLS);
        // import
        $file = new CsvFile(self::DATA_DIR . 'with-ts.csv');
        $source = $this->getSourceInstance('with-ts.csv', $file->getHeader());
        $destination = new Storage\Bigquery\Table(
            $this->getDestinationDbName(),
            self::TABLE_OUT_CSV_2COLS,
        );

        $this->importTable($source, $destination);

        // export
        $source = $destination;
        $options = new ExportOptions(true, ExportOptions::MANIFEST_AUTOGENERATED);
        $destination = $this->getDestinationInstance($this->getExportDir() . '/gz_test');

        (new Exporter($this->bqClient))->exportTable(
            $source,
            $destination,
            $options,
        );

        $files = $this->getFileNames($this->getExportDir() . '/gz_test', false);
        sort($files);
        $expected = [
            $this->getExportDir() . '/gz_test000000000000.csv.gz',
            $this->getExportDir() . '/gz_test000000000001.csv.gz',
            $this->getExportDir() . '/gz_testmanifest',
        ];
        sort($expected);
        $this->assertSame($expected, $files);
    }

    public function testExportSimple(): void
    {
        $this->initTable(self::TABLE_OUT_CSV_2COLS);
        // import
        $file = new CsvFile(self::DATA_DIR . 'with-ts.csv');
        $source = $this->getSourceInstance('with-ts.csv', $file->getHeader());
        $destination = new Storage\Bigquery\Table(
            $this->getDestinationDbName(),
            self::TABLE_OUT_CSV_2COLS,
        );
        $this->importTable($source, $destination);

        // export
        $source = $destination;
        $options = new ExportOptions(false, ExportOptions::MANIFEST_AUTOGENERATED);
        $destination = $this->getDestinationInstance($this->getExportDir() . '/ts_test');

        (new Exporter($this->bqClient))->exportTable(
            $source,
            $destination,
            $options,
        );

        $files = $this->listFiles($this->getExportDir());
        $actual = $this->getCsvFileFromStorage($files);
        $expected = new CsvFile(
            self::DATA_DIR . 'with-ts.expected.bigquery.csv',
            CsvOptions::DEFAULT_DELIMITER,
            CsvOptions::DEFAULT_ENCLOSURE,
            CsvOptions::DEFAULT_ESCAPED_BY,
            1, // skip header
        );
        $this->assertCsvFilesSame($expected, $actual);

        $files = $this->getFileNames($this->getExportDir(), false);
        $this->assertContains($this->getExportDir() . '/ts_testmanifest', array_values($files));
    }

    public function assertCsvFilesSame(CsvFile $expected, CsvFile $actual): void
    {
        $this->assertArrayEqualsSorted(
            iterator_to_array($expected),
            iterator_to_array($actual),
            0,
            'Csv files are not same',
        );
    }

    public function testExportSimpleWithQuery(): void
    {
        $this->initTable(self::TABLE_ACCOUNTS_3);
        // import
        $file = new CsvFile(self::DATA_DIR . 'tw_accounts.csv');
        $source = $this->getSourceInstance('tw_accounts.csv', $file->getHeader());
        $destination = new Storage\Bigquery\Table(
            $this->getDestinationDbName(),
            self::TABLE_ACCOUNTS_3,
        );

        $this->importTable($source, $destination);

        // export
        // query needed otherwise timestamp is downloaded
        $query = sprintf(
            'SELECT %s FROM %s',
            implode(',', $file->getHeader()),
            $destination->getQuotedTableWithScheme(),
        );
        $source = new Storage\Bigquery\SelectSource($query);
        $options = new ExportOptions(false, ExportOptions::MANIFEST_AUTOGENERATED);
        $destination = $this->getDestinationInstance($this->getExportDir() . '/tw_test');

        (new Exporter($this->bqClient))->exportTable(
            $source,
            $destination,
            $options,
        );

        $files = $this->listFiles($this->getExportDir());
        $actual = $this->getCsvFileFromStorage($files);
        $expected = new CsvFile(
            self::DATA_DIR . 'tw_accounts.csv',
            CsvOptions::DEFAULT_DELIMITER,
            CsvOptions::DEFAULT_ENCLOSURE,
            CsvOptions::DEFAULT_ESCAPED_BY,
            1, // skip header
        );
        $this->assertCsvFilesSame($expected, $actual);

        $files = $this->getFileNames($this->getExportDir(), false);
        $this->assertContains($this->getExportDir() . '/tw_testmanifest', array_values($files));
    }

    private function importTable(
        Storage\SourceInterface $source,
        Storage\Bigquery\Table $destination,
    ): void {
        $options = $this->getSimpleImportOptions(ImportOptions::SKIP_FIRST_LINE);
        $importer = new ToStageImporter($this->bqClient);
        $destinationRef = new BigqueryTableReflection(
            $this->bqClient,
            $destination->getSchema(),
            $destination->getTableName(),
        );
        /** @var BigqueryTableDefinition $importDestination */
        $importDestination = $destinationRef->getTableDefinition();
        $stagingTable = StageTableDefinitionFactory::createStagingTableDefinition(
            $importDestination,
            $source->getColumnsNames(),
        );
        $qb = new BigqueryTableQueryBuilder();
        $this->bqClient->runQuery($this->bqClient->query(
            $qb->getCreateTableCommandFromDefinition($stagingTable),
        ));
        $importState = $importer->importToStagingTable(
            $source,
            $stagingTable,
            $options,
        );
        $toFinalTableImporter = new FullImporter($this->bqClient);

        $toFinalTableImporter->importToTable(
            $stagingTable,
            $importDestination,
            $options,
            $importState,
        );
    }
}
