name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Build Image
        run: docker-compose build

      - name: Run Tests
        run: dc run --rm production composer ci
