name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Build Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
        run: docker-compose build

      - name: Run Tests
        env:
          TERADATA_HOST: ${{ secrets.TERADATA_HOST }}
          TERADATA_USERNAME: ${{ secrets.TERADATA_USERNAME }}
          TERADATA_PASSWORD: ${{ secrets.TERADATA_PASSWORD }}
          TERADATA_PORT: 1025
          TERADATA_ROOT_DATABASE: ci_driver_teradata
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: docker-compose run --rm production composer ci
