on:
  workflow_call:
    inputs:
      hasCodeChanged:
        required: true
        type: boolean
      isTag:
        required: true
        type: boolean
    secrets:
      SNOWFLAKE_PASSWORD:
        required: true
      SNOWFLAKE_PRIVATE_KEY:
        required: true

concurrency: build-php-storage-driver-snowflake

env:
  SNOWFLAKE_HOST: keboolaconnectiondev.us-east-1.snowflakecomputing.com
  SNOWFLAKE_PORT: 443
  SNOWFLAKE_USER: KEBOOLA_CI_PHP_STORAGE_DRIVER_SNOWFLAKE
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
  SNOWFLAKE_DATABASE: KEBOOLA_CI_PHP_STORAGE_DRIVER_SNOWFLAKE
  SNOWFLAKE_WAREHOUSE: DEV

jobs:
  build:
    if: ${{ inputs.hasCodeChanged || inputs.isTag }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: docker compose build ci-php-storage-driver-snowflake

      - name: Run tests
        run: docker compose run --rm ci-php-storage-driver-snowflake composer ci
